# Beispiel-Setupdatei für EXIF UserComment
[App]
Standard=Chaosbox

[App.Chaosbox]
Titel=Chaosbox
JPG=ChaosBox/JPG
Daten=ChaosBox/boxes
Felder=Box,Anzahl,Device,Alias,Kategorie,Kommentar,Package
Kategorie=Heizung, Wasser, Elektro, Maurer, Fliesen, Garten, Elektronikbauteile, El-Baugruppen, Haushalt

[App.Bilderbox]
Titel=Bilderbox
JPG=Bilderbox/JPG
Daten=Bilderbox/boxes
Felder=Box,,,Tags,Kategorie,Kommentar
Kategorie=Heizung, Wasser, Elektro, Maurer, Fliesen, Garten, Elektronikbauteile, El-Baugruppen, Haushalt
# JPGs liegen eine Ebene tiefer: <kategorie in klein> oder unassigned; JSON bleibt in boxes.

[ImageSize]
LIMIT=3000

[TextSnippets]
text1="text1"
text2="text2"
